name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin CI...
        uses: actions/checkout@v2

      - name: Use Node 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache Dist folder
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-cache-dist
          restore-keys: |
            ${{ runner.os }}-cache-dist

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Lint
        run: yarn lint
        env:
          CI: true

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          CI: true

      - name: Build
        run: yarn build
        env:
          CI: true

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Get branch code
        uses: actions/checkout@v2

      - name: Cache Dist folder
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-cache-dist
          restore-keys: |
            ${{ runner.os }}-cache-dist

      - name: Copy Files
        run: |
          mkdir public
          cp index.html public/
          cp -R assets/ public/assets/
          cp -R dist/ public/dist/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.7.0-8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          keep_files: true
